### ISSUE TITLE
IDE

### ISSUE THREAD

**Issue by ThePMO** [Boris-de/upod#1]
Hi!,
I also want to continue to use uPod and also to add some features I've always wanted. I'm new to Scala and was not able to compile Svens project in any way so I'm thankfull that you provided the first buildable version I could actually use.

Now I wanted to ask how you develop this project or Scala on Android in general, which IDE do you use, how do you debug etc.

The gradle-android-scala-plugin doesn't work at all with newer SDKs/Gradle.
sbt compiles and can install the debug apk but I'm not able to debug the application (debugger never attaches). The android:run command has been removed somehow in this project??

Neither Android Studio nor IntellyJ IDEA nor plain sbt shell work for me, I'm pretty much at a loss here...

**Comment by Boris-de** [comment]
Hi,

I'm using Intellij IDEA with the Scala plugin. I opened it as an sbt project, not as a gradle project. I'm not sure if I had to do something special, nothing that I could remember.

It's not really working well, but I'm able to work on the main app with code-completion&co. But the modules are missing the android-dependencies for some reason, which gives you many compilation errors if you open files in there. I don't know why that is, the sbt configuration for those modules looks just like the app's configuration. Could just be, that Intellij's sbt integration is able to work with "AndroidApp", but not with "AndroidLib".

Which IDEA version are you using? I have the latest 2018.3 and use the "Ultimate" version, which gives you more features in the scala-plugin, but the list is very short and there is nothing in there that should make any difference for this project (Play Framework, Akka and Scala.js)

I haven't tried debug or something like android:run yet. Up to now I just did a debug build and put it on my old phone. I did nothing yet where I feeled the need for a proper debug mode. I'll give it a try.

Cheers,
Boris

**Comment by Boris-de** [comment]
I tried to import the project from a different location, here is what I did: "New -> Project from existing sources" -> select folder -> select "sbt" -> select a Java 8 SDK (keep the other settings, which was "Allow override sbt version" and "download library sources" checked). That imported the project with the limitations mentioned above.
It did not work when selecting an Android SDK because then sbt would run with my default Java 11 although Java 8 is configured for the Android SDK.

Regarding debug: What worked easily is to install the debug build on a device (possible also the emulator), run it and use "Run -> Attach debugger to Android process" in Intellij. This should list the running app and you can debug it with the "Java"-Debugger.
That way I could set a breakpoint in the Scala code and use the usual Intellij features.

I did not see an (easy) way to configure Intellij in a way that could automatically install on a device/emulator, there is no artifact to select. And of course the modules are not building, which Intellij tries to do.

I forget to mention earlier that I'm running linux.

**Comment by ThePMO** [comment]
I can confirm that this also works on Win10 using IntelliJ IDEA Community 18.3, thank you!
